config/routes.rb
Visionopolis5::Application.routes.draw do
  resources :beats

  match 'images/gallery' => "images#gallery", :as => :gallery
  resources :images
  root :to => "images#new"
  

  

end

app/models/beat.rb
class Beat < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
has_attached_file :photo
belongs_to :beat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_filter :verify_authenticity_token
end

app/controllers/beats_controller.rb
class BeatsController < ApplicationController
  # GET /beats
  # GET /beats.xml
  def index
    @beats = Beat.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @beats }
    end
  end

  # GET /beats/1
  # GET /beats/1.xml
  def show
    @beat = Beat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @beat }
    end
  end

  # GET /beats/new
  # GET /beats/new.xml
  def new
    @beat = Beat.new
    @sounds = Image.find(Image.all(:select => :id).map(&:id).sort_by{rand}[0..10])
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @beat }
    end
  end

  # GET /beats/1/edit
  def edit
    @beat = Beat.find(params[:id])
  end

  # POST /beats
  # POST /beats.xml
  def create
    @beat = Beat.new(params[:beat])

    respond_to do |format|
      if @beat.save
        format.html { redirect_to(@beat, :notice => 'Beat was successfully created.') }
        format.xml  { render :xml => @beat, :status => :created, :location => @beat }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @beat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /beats/1
  # PUT /beats/1.xml
  def update
    @beat = Beat.find(params[:id])

    respond_to do |format|
      if @beat.update_attributes(params[:beat])
        format.html { redirect_to(@beat, :notice => 'Beat was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @beat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /beats/1
  # DELETE /beats/1.xml
  def destroy
    @beat = Beat.find(params[:id])
    @beat.destroy

    respond_to do |format|
      format.html { redirect_to(beats_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.xml
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @images }
    end
  end
  
  # def gallery
  #       @images = Image.all
  #       @lat = params[:lat].to_f
  #       @long = params[:long].to_f
  #       @images.each do |image|
  #       @nearby = []
  #       @images.each do |image|
  #       if (image.Latitude - @lat)**2 + (image.Longitude - @long)**2 < 1
  #        @nearby << image
  #       end
  #       @nearby = @nearby.sort_by { rand }
  #       end

#<% if nearby.length >= 1 %>
#<p><%= image_tag nearby[0].photo.url %></p>
#end
#<% end %>
	
	
	
  #       respond_to do |format|
  #     format.html # index.html.erb
  #     format.xml  { render :xml => @images }
  #   end
  # end

  # GET /images/1
  # GET /images/1.xml
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/new
  # GET /images/new.xml
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.xml
  def create
    @image = Image.new(params[:image])
   
    

    respond_to do |format|
      if @image.save
        format.html { redirect_to(@image, :notice => 'Image was successfully created.') }
        format.xml  { render :xml => @image, :status => :created, :location => @image }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.xml
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to(@image, :notice => 'Image was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.xml
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to(images_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beats_helper.rb
module BeatsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/beats/_form.html.erb
<%= form_for(@beat) do |f| %>
  <% if @beat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beat.errors.count, "error") %> prohibited this beat from being saved:</h2>

      <ul>
      <% @beat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.text_field :length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beats/edit.html.erb
<h1>Editing beat</h1>

<%= render 'form' %>

<%= link_to 'Show', @beat %> |
<%= link_to 'Back', beats_path %>

app/views/beats/index.html.erb
<h1>Listing beats</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Length</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @beats.each do |beat| %>
  <tr>
    <td><%= beat.name %></td>
    <td><%= beat.length %></td>
    <td><%= link_to 'Show', beat %></td>
    <td><%= link_to 'Edit', edit_beat_path(beat) %></td>
    <td><%= link_to 'Destroy', beat, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beat', new_beat_path %>

app/views/beats/new.html.erb
<head>

<script type="text/javascript">
var idcount = 1
function soundoff(source){
putsound(source);

idcount = idcount+1
}

function putsound(source){
var n = document.createElement('audio');
n.setAttribute('autoplay', 'autoplay')
n.setAttribute('id', idcount)
n.setAttribute('controls', 'controls')
n.setAttribute('style', 'visibility: hidden')
n.setAttribute('onplaying', 'timeoutsound(this,5)')

n.innerHTML = '<source src='+source+' />'
document.body.insertBefore(n,document.getElementById("0"))


}

function timeoutsound(audio,time){
setTimeout(function (){audio.play();}, time*1000)
}
</script>

</head>
<h1>New image</h1>

<% for sound in @sounds %>
<button type="button" onclick="<%= "soundoff(\"#{sound.photo.url}\")" %>"> <%= sound.photo_id %></button>
<% end %>

<div id="0">
me
</div>
<audio autoplay="autoplay" controls="controls" style="visibility: hidden" onplaying="timeoutsound(this,3)"> 
    <source src="/system/photos/3/original/sly2.wav" /> 
</audio> 
<%= link_to 'Back', images_path %>

app/views/beats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @beat.name %>
</p>

<p>
  <b>Length:</b>
  <%= @beat.length %>
</p>


<%= link_to 'Edit', edit_beat_path(@beat) %> |
<%= link_to 'Back', beats_path %>

app/views/images/_form.html.erb
<% form_for(@image,:html => { :multipart => true }) do |f| %>  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  </div>
  <div class="field">
    <%= f.label :photo_id %><br />
    <%= f.text_field :photo_id %>
  </div>
    <div class="field">
    <%= f.label :photo_file_name %><br />
    <%= f.text_field :photo_file_name %>
  </div>
  <p>
  <%= f.label 'Photo' %><br />
  <%= f.file_field :photo %>
</p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/_locationform.erb
<%= form_tag :gallery do %>
  <%= text_field_tag "lat", "Enter your latitude" %>
    <%= text_field_tag "long", "Enter your longitude" %>
  <%= submit_tag "Go" %>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/gallery.html.erb
<h1>Visionopolis</h1>

<% if @nearby.length > 0 %>
<% @nearby.sort_by { rand }%> <p><%= image_tag @nearby[0].photo.url %></p>
<% end %>

<%= link_to 'Back', images_path %>

<br />

<%= link_to 'New Image', new_image_path %>

app/views/images/index.html.erb
<h1>Visionopolis</h1>
<% x=0 %>
<% @images.each do |image| x += 1 end %>
<% if x >= 1 then %>
<table cellpadding = '10'>
  <tr>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Caption</th>
<!--    <th>Photo</th> -->
	<th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= image.Latitude %></td>
    <td><%= image.Longitude %></td>
    <td><%= image.caption %></td>
  <!--  <td><%= image.photo_id %></td> -->
	<td>
<p><%= image_tag image.photo.url %></p>
</td>
    <td><%= link_to 'Show', image %></td>
    <td><%= link_to 'Edit', edit_image_path(image) %></td>
    <td><%= link_to 'Destroy', image, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>

<% end %>
</table>


<%= render 'locationform' %>

<%= link_to 'Back', images_path %>


<% else %>
<p> There are no photo's attached mayn, upload one. </p>
<% end %>
<br />

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Photo:</b>
  <%= @image.photo_id %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Visionopolis</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>